CREATE_TABLES = {
    "sale_order_line": """
        CREATE TABLE IF NOT EXISTS sale_order_line (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_reference TEXT NOT NULL,
            sku TEXT NOT NULL,
            product TEXT,
            collection TEXT,
            product_template TEXT,
            product_category TEXT,
            fabric_sku TEXT,
            fabric_type TEXT,
            quantity INTEGER,
            subtotal REAL,
            total_cost REAL,
            unit_cost REAL,
            unit_price REAL,
            order_status TEXT,
            invoice_status TEXT,
            delivery_status TEXT,
            FOREIGN KEY (sku) REFERENCES master_sku (sku)
        );
    """,
    "master_sku": """
        CREATE TABLE IF NOT EXISTS master_sku (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            collection TEXT,
            fabric_code TEXT,
            sku_parent TEXT,
            sku TEXT UNIQUE NOT NULL,
            name TEXT,
            season TEXT,
            faho24_status TEXT,
            spsu25_status TEXT,
            sold_by_info TEXT,
            carded_non_carded TEXT,
            card_properties TEXT,
            properties TEXT,
            stones TEXT,
            color TEXT,
            cord_print_pattern TEXT,
            material TEXT,
            length TEXT,
            size TEXT,
            size_abbreviation TEXT,
            unit_cost REAL,
            ws_price REAL,
            ec_price REAL,
            weight_lbs REAL,
            upc TEXT,
            min_qty INTEGER,
            ws_sku BOOLEAN,
            ec_sku BOOLEAN,
            amazon_sku TEXT,
            vendor TEXT,
            bom_category TEXT,
            yards_per_unit REAL,
            labor_cost REAL,
            card_sku TEXT,
            prefix TEXT,
            prepack_sku TEXT,
            prepack_assortment_qty TEXT,
            available_sizes TEXT
        );
    """
}
